// src/mockData.js

// Mock tasks that feed into the queue from various sources
export const mockTasks = [
  {
    id: 'task-1',
    title: 'Finish Git module',
    source: 'Project',
    sourceType: 'project',
    deadline: '2026-07-23',
    priority: 'high',
    completed: false,
    stuck: false,
    stuckReason: '',
  },
  {
    id: 'task-2',
    title: 'Write LinkedIn post',
    source: 'Routine',
    sourceType: 'routine',
    deadline: '2026-07-21',
    priority: 'medium',
    completed: false,
    stuck: false,
    stuckReason: '',
  },
  {
    id: 'task-3',
    title: 'Submit OSS PR to Carto',
    source: 'Community',
    sourceType: 'community',
    deadline: '2026-07-24',
    priority: 'medium',
    completed: false,
    stuck: false,
    stuckReason: '',
  },
  {
    id: 'task-4',
    title: 'Learn React — useEffect',
    source: 'Learning',
    sourceType: 'learning',
    deadline: null,
    priority: 'low',
    completed: false,
    stuck: false,
    stuckReason: '',
  },
  {
    id: 'task-5',
    title: 'Reply to mentor feedback',
    source: 'Mentor',
    sourceType: 'mentor',
    deadline: '2026-07-21',
    priority: 'high',
    completed: false,
    stuck: false,
    stuckReason: '',
  },
];

// Mock routines for "Today's Routines"
export const mockRoutines = [
  {
    id: 'routine-1',
    title: 'Daily Coding Practice',
    frequency: 'daily',
    timeStart: '09:00',
    timeEnd: '10:00',
    completed: true,
    currentCount: 30,
    targetCount: 30,
  },
  {
    id: 'routine-2',
    title: 'Weekly LinkedIn Post',
    frequency: 'weekly',
    timeStart: '14:00',
    timeEnd: '15:00',
    completed: false,
    currentCount: 0,
    targetCount: 4,
  },
  {
    id: 'routine-3',
    title: 'Weekly OSS Contribution',
    frequency: 'weekly',
    timeStart: '15:00',
    timeEnd: '16:00',
    completed: false,
    currentCount: 0,
    targetCount: 4,
  },
];
